#!/usr/bin/env python3
"""
compute_metrics.py

Read benchmark result artifacts and export all evaluation metrics to CSV.

Supported inputs:
1. results.json generated by the benchmark runner

Outputs:
- metrics_summary.csv: config-level metrics
- metrics_per_prompt.csv: per-prompt metrics incl. quality

Notes:
- E2E latency, throughput, RAM, and quality are computed directly from results.
- TTFT and ITL are exported if present in request records; otherwise left blank.
- Quality uses exact match and token-F1 if outputs are available for both configs.
"""

import argparse
import csv
import json
import re
import statistics
from pathlib import Path
from typing import Dict, List, Any, Tuple


def percentile(values: List[float], pct: float) -> float:
    if not values:
        return 0.0
    s = sorted(values)
    k = (len(s) - 1) * pct / 100.0
    lo = int(k)
    hi = min(lo + 1, len(s) - 1)
    return s[lo] + (k - lo) * (s[hi] - s[lo])


def token_f1(text_a: str, text_b: str) -> float:
    tok_a = set(re.findall(r"\b\w+\b", (text_a or "").lower()))
    tok_b = set(re.findall(r"\b\w+\b", (text_b or "").lower()))
    if not tok_a or not tok_b:
        return 0.0
    common = tok_a & tok_b
    precision = len(common) / len(tok_b)
    recall = len(common) / len(tok_a)
    if precision + recall == 0:
        return 0.0
    return 2 * precision * recall / (precision + recall)


def exact_match(text_a: str, text_b: str) -> int:
    return int((text_a or "").strip() == (text_b or "").strip())


def load_json(path: Path) -> Dict[str, Any]:
    with path.open("r", encoding="utf-8") as f:
        return json.load(f)


def get_requests(section: Dict[str, Any]) -> List[Dict[str, Any]]:
    reqs = section.get("requests")
    if isinstance(reqs, list):
        return reqs
    return []


def get_outputs(section: Dict[str, Any]) -> Dict[str, str]:
    outputs = section.get("outputs")
    if isinstance(outputs, dict):
        return outputs
    reqs = get_requests(section)
    out = {}
    for r in reqs:
        pid = r.get("prompt_id")
        if pid is not None:
            out[pid] = r.get("output", "")
    return out


def summarize_config(name: str, section: Dict[str, Any]) -> Dict[str, Any]:
    summary = section.get("summary", {})
    requests = get_requests(section)

    if summary:
        return {
            "config_name": name,
            "ttft_p50_ms": summary.get("ttft_p50_ms", ""),
            "ttft_p95_ms": summary.get("ttft_p95_ms", ""),
            "ttft_p99_ms": summary.get("ttft_p99_ms", ""),
            "itl_p50_ms": summary.get("itl_p50_ms", ""),
            "itl_p95_ms": summary.get("itl_p95_ms", ""),
            "itl_p99_ms": summary.get("itl_p99_ms", ""),
            "e2e_p50_ms": summary.get("e2e_p50_ms", ""),
            "e2e_p95_ms": summary.get("e2e_p95_ms", ""),
            "e2e_p99_ms": summary.get("e2e_p99_ms", ""),
            "avg_tokens_per_second": summary.get("avg_tps", ""),
            "peak_ram_mb": summary.get("peak_ram_mb", ""),
            "total_tokens": summary.get("total_tokens", ""),
            "num_requests": summary.get("num_requests", len(requests)),
        }

    e2e = [r.get("e2e_ms") for r in requests if r.get("e2e_ms") is not None]
    tps = [r.get("tokens_per_second") for r in requests if r.get("tokens_per_second") is not None]
    ram_vals = [r.get("ram_mb_after") for r in requests if r.get("ram_mb_after") is not None]
    ttft = [r.get("ttft_ms") for r in requests if r.get("ttft_ms") is not None]
    itl = [r.get("avg_itl_ms") for r in requests if r.get("avg_itl_ms") is not None]
    total_tokens = sum(r.get("tokens_generated", 0) or 0 for r in requests)

    return {
        "config_name": name,
        "ttft_p50_ms": percentile(ttft, 50) if ttft else "",
        "ttft_p95_ms": percentile(ttft, 95) if ttft else "",
        "ttft_p99_ms": percentile(ttft, 99) if ttft else "",
        "itl_p50_ms": percentile(itl, 50) if itl else "",
        "itl_p95_ms": percentile(itl, 95) if itl else "",
        "itl_p99_ms": percentile(itl, 99) if itl else "",
        "e2e_p50_ms": percentile(e2e, 50) if e2e else "",
        "e2e_p95_ms": percentile(e2e, 95) if e2e else "",
        "e2e_p99_ms": percentile(e2e, 99) if e2e else "",
        "avg_tokens_per_second": statistics.mean(tps) if tps else "",
        "peak_ram_mb": max(ram_vals) if ram_vals else section.get("peak_ram_mb", ""),
        "total_tokens": total_tokens,
        "num_requests": len(requests),
    }


def build_per_prompt_rows(baseline: Dict[str, Any], turbo: Dict[str, Any]) -> List[Dict[str, Any]]:
    b_reqs = {r.get("prompt_id"): r for r in get_requests(baseline)}
    t_reqs = {r.get("prompt_id"): r for r in get_requests(turbo)}
    b_outputs = get_outputs(baseline)
    t_outputs = get_outputs(turbo)

    prompt_ids = sorted(set(list(b_reqs.keys()) + list(t_reqs.keys()) + list(b_outputs.keys()) + list(t_outputs.keys())))
    rows = []
    for pid in prompt_ids:
        br = b_reqs.get(pid, {})
        tr = t_reqs.get(pid, {})
        b_out = b_outputs.get(pid, br.get("output", ""))
        t_out = t_outputs.get(pid, tr.get("output", ""))

        rows.append({
            "prompt_id": pid,
            "baseline_ttft_ms": br.get("ttft_ms", ""),
            "turboquant_ttft_ms": tr.get("ttft_ms", ""),
            "baseline_avg_itl_ms": br.get("avg_itl_ms", ""),
            "turboquant_avg_itl_ms": tr.get("avg_itl_ms", ""),
            "baseline_e2e_ms": br.get("e2e_ms", ""),
            "turboquant_e2e_ms": tr.get("e2e_ms", ""),
            "baseline_tokens_per_second": br.get("tokens_per_second", ""),
            "turboquant_tokens_per_second": tr.get("tokens_per_second", ""),
            "baseline_ram_mb": br.get("ram_mb_after", ""),
            "turboquant_ram_mb": tr.get("ram_mb_after", ""),
            "exact_match": exact_match(b_out, t_out),
            "token_f1": token_f1(b_out, t_out),
            "baseline_truncated": br.get("truncated", ""),
            "turboquant_truncated": tr.get("truncated", ""),
        })
    return rows


def build_quality_summary(rows: List[Dict[str, Any]]) -> Tuple[float, float]:
    if not rows:
        return "", ""
    avg_exact = statistics.mean([r["exact_match"] for r in rows])
    avg_f1 = statistics.mean([r["token_f1"] for r in rows])
    return avg_exact, avg_f1


def write_csv(path: Path, rows: List[Dict[str, Any]]) -> None:
    if not rows:
        return
    with path.open("w", newline="", encoding="utf-8") as f:
        writer = csv.DictWriter(f, fieldnames=list(rows[0].keys()))
        writer.writeheader()
        writer.writerows(rows)


def main():
    parser = argparse.ArgumentParser(description="Compute benchmark metrics and export CSV files.")
    parser.add_argument("--results", required=True, help="Path to results.json")
    parser.add_argument("--output-dir", default="results", help="Directory for CSV outputs")
    args = parser.parse_args()

    results_path = Path(args.results)
    output_dir = Path(args.output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)

    data = load_json(results_path)
    baseline = data.get("baseline", {})
    turbo = data.get("turboquant", {})

    baseline_summary = summarize_config("baseline", baseline)
    turbo_summary = summarize_config("turboquant", turbo)

    per_prompt_rows = build_per_prompt_rows(baseline, turbo)
    avg_exact, avg_f1 = build_quality_summary(per_prompt_rows)

    summary_rows = [
        {
            "config_name": "baseline",
            **baseline_summary,
            "avg_exact_match": "",
            "avg_token_f1": "",
        },
        {
            "config_name": "turboquant",
            **turbo_summary,
            "avg_exact_match": "",
            "avg_token_f1": "",
        },
        {
            "config_name": "quality_comparison",
            "ttft_p50_ms": "",
            "ttft_p95_ms": "",
            "ttft_p99_ms": "",
            "itl_p50_ms": "",
            "itl_p95_ms": "",
            "itl_p99_ms": "",
            "e2e_p50_ms": "",
            "e2e_p95_ms": "",
            "e2e_p99_ms": "",
            "avg_tokens_per_second": "",
            "peak_ram_mb": "",
            "total_tokens": "",
            "num_requests": len(per_prompt_rows),
            "avg_exact_match": avg_exact,
            "avg_token_f1": avg_f1,
        },
    ]

    keys = [
        "config_name",
        "ttft_p50_ms", "ttft_p95_ms", "ttft_p99_ms",
        "itl_p50_ms", "itl_p95_ms", "itl_p99_ms",
        "e2e_p50_ms", "e2e_p95_ms", "e2e_p99_ms",
        "avg_tokens_per_second",
        "peak_ram_mb",
        "total_tokens",
        "num_requests",
        "avg_exact_match",
        "avg_token_f1",
    ]

    normalized_summary = [{k: row.get(k, "") for k in keys} for row in summary_rows]

    write_csv(output_dir / "metrics_summary.csv", normalized_summary)
    write_csv(output_dir / "metrics_per_prompt.csv", per_prompt_rows)

    print(f"Wrote: {output_dir / 'metrics_summary.csv'}")
    print(f"Wrote: {output_dir / 'metrics_per_prompt.csv'}")


if __name__ == "__main__":
    main()